<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

use Doctrine\ORM\Mapping;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em, $metaData == null ?
            new Mapping\ClassMetadata(Product::class) : $metaData);
    }

    /**
     * @param Product $product
     * @return bool
     * @throws ORMException
     */
    public function insert(Product $product)
    {
        try {
            $this->_em->persist($product);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Product $product
     * @return bool
     * @throws ORMException
     */
    public function update(Product $product)
    {
        try {
            $this->_em->merge($product);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Product $product
     * @return bool
     * @throws ORMException
     */
    public function remove(Product $product)
    {
        try {
            $this->_em->remove($product);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
